AWSTemplateFormatVersion: '2010-09-09'
Description: Launch a simple EC2 instance based on region mapping

Parameters:
  Imageami:
    Type: String
    Description: AMI ID to launch the EC2 instance

  Env:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: Environment name used for tagging

Mappings:
  RegionInstanceTypeMap:
    ap-southeast-2:
      InstanceType: t2.micro
    ap-southeast-1:
      InstanceType: t3.micro

Resources:
  myInstance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref Imageami
      InstanceType: !FindInMap 
        - RegionInstanceTypeMap
        - !Ref "AWS::Region"
        - InstanceType
      Tags:
        - Key: Name
          Value: !Sub "ec2-${Env}-instance"
        - Key: Environment
          Value: !Ref Env
